---
- name: log
  hosts: all
  become: yes

  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: latest
      update_cache: yes
    when: ansible_hostname == "web"

  - name: edit /etc/rsyslog.conf
    lineinfile:
      dest: /etc/rsyslog.conf
      regex: '^#\s*{{ item.regex }}(.*)$'
      line: '{{ item.replace }}'
    loop:
      - regex: module(load="imudp")
        replace: module(load="imudp")
      - regex: input(type="imudp" port="514")
        replace: input(type="imudp" port="514")
      - regex: module(load="imtcp")
        replace: module(load="imtcp")
      - regex: input(type="imtcp" port="514")
        replace: input(type="imtcp" port="514")
    when: ansible_hostname == "log" 

  - name: add lines in /etc/rsyslog.conf
    blockinfile:
      path: /etc/rsyslog.conf
      block: |
        $template RemoteLogs,"/var/log/rsyslog/%HOSTNAME%/%PROGRAMNAME%.log"
        *.* ?RemoteLogs
    when: ansible_hostname == "log" 

  - name: restart rsyslog service
    service: 
      name: rsyslog
      state: restarted
    when: ansible_hostname == "log"
      