---
- name: log
  hosts: all
  become: yes
  vars_files: env/env.yml
 
  tasks:
  - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
  when: ansible_hostname == "web"